theme: jekyll-theme-architect

lsi: false
 safe: true
 source: [your repo's top level directory]
 incremental: false
 highlighter: rouge
 gist:
   noscript: false
 kramdown:
   math_engine: mathjax
   
   
title: This is my title
layout: post

Here is my page.

